# Generated by Django 3.1.2 on 2020-11-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phonenumber',
            field=models.TextField(max_length=30, null=True, unique=True),
        ),
    ]
