# Generated by Django 3.1.2 on 2020-11-13 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='products/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.restaurant')),
            ],
        ),
    ]
