# Generated by Django 3.1.2 on 2020-11-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
