# Generated by Django 3.1.2 on 2020-11-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201113_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rimage',
            field=models.ImageField(default=0, upload_to='uploads/restaurants'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
    ]
