# Generated by Django 3.1.2 on 2020-11-17 06:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Myorder',
        ),
    ]
